# Generated by Django 3.2.5 on 2022-02-18 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('name', models.CharField(max_length=40)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
