# Generated by Django 3.2.5 on 2022-02-18 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0003_alter_address_pincode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='pincode',
        ),
    ]
