# Generated by Django 3.2.5 on 2022-02-18 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0005_demo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adddetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=6)),
            ],
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
