# Generated by Django 3.2.5 on 2022-02-18 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('googlepay', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Payment_details',
            new_name='Googlepay_details',
        ),
    ]
