# Generated by Django 3.2.5 on 2022-02-21 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('Student_name', models.CharField(max_length=40)),
                ('Student_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Telugu_marks', models.IntegerField()),
                ('English_marks', models.IntegerField()),
                ('kannada_marks', models.IntegerField()),
                ('Hindi_marks', models.IntegerField()),
                ('Maths_marks', models.IntegerField()),
                ('Science_marks', models.IntegerField()),
            ],
        ),
    ]
